var data = [
  { city: '上海', name: '上海市闵行区中医院', link: 'http://www.tcmmh.com/' },
  {
    city: '上海',
    name: '上海华美美莱整形医院',
    link: 'http://www.shhuamei.cn/',
  },
  { city: '上海', name: '上海万众医院', link: 'http://www.wz120.cc/' },
  { city: '上海', name: '上海安真医院', link: 'http://2062.hos.zx7b.com/' },
  { city: '上海', name: '上海福华医院', link: 'http://2059.hos.zx7b.com/' },
  {
    city: '上海',
    name: '上海玛丽女子医院',
    link: 'http://1082758.1024sj.com/',
  },
  {
    city: '上海',
    name: '上海真爱女子医院',
    link: 'http://shanghai357817.cn.cnlinfo.net/',
  },
  { city: '上海', name: '上海心脏病医院', link: '' },
  { city: '上海', name: '上海沪申五官科医院', link: 'http://www.hs5g.com/' },
  { city: '上海', name: '上海远大心胸医院', link: 'http://www.yodak.net/' },
  { city: '上海', name: '上海仁爱医院', link: '' },
  {
    city: '上海',
    name: '上海天大医疗美容医院',
    link: 'http://www.tida.sh.cn/',
  },
  { city: '上海', name: '上海博爱医院', link: 'http://www.boaihospital.com/' },
  { city: '上海', name: '上海新虹桥医院', link: 'http://www.shhqyy.com/' },
  {
    city: '上海',
    name: '上海九龙男子医院',
    link: 'http://health.shlong120.cn/',
  },
  {
    city: '上海',
    name: '上海城市女子医院',
    link: 'http://shanghai292334.cn.cnlinfo.net/',
  },
  { city: '上海', name: '上海西郊骨科医院', link: '' },
  { city: '上海', name: '上海真美妇科医院', link: 'http://www.npswj.com/' },
  { city: '上海', name: '上海南浦妇科医院', link: 'http://www.bjtjgp.com/' },
  { city: '上海', name: '上海虹桥医院', link: 'http://www.shhqyy.com/' },
  {
    city: '上海',
    name: '上海健桥医院',
    link: 'http://www.jianqiaohospital.com/',
  },
  { city: '上海', name: '上海博爱医院', link: '' },
  { city: '上海', name: '上海长江医院', link: '' },
  { city: '上海', name: '解放军411医院', link: '' },
  { city: '上海', name: '上海阳光中医医院', link: '' },
  { city: '上海', name: '上海英港泌尿外科医院', link: '' },
  { city: '上海', name: '上海阿波罗男子医院', link: '' },
  { city: '上海', name: '上海玫瑰女子医院', link: '' },
  { city: '上海', name: '上海康新医院', link: '' },
  { city: '上海', name: '上海圣爱医院', link: '' },
  { city: '上海', name: '上海同德医院', link: '' },
  { city: '上海', name: '上海安平医院', link: '' },
  { city: '上海', name: '江东泌尿外科医院', link: '' },
  { city: '上海', name: '上海九州泌尿医院', link: '' },
  { city: '上海', name: '上海青城医院', link: '' },
  { city: '上海', name: '上海博大医院', link: '' },
  { city: '上海', name: '上海中亚医院', link: '' },
  {
    city: '北京',
    name: '北京华美美莱整形医院',
    link: 'http://www.bjmylike.com/',
  },
  { city: '北京', name: '北京俪人女子医院', link: '' },
  { city: '北京', name: '北京北海医院', link: 'http://wailian.bho1.com/' },
  { city: '北京', name: '北京前海股骨头医院', link: 'http://www.qianhai.com/' },
  {
    city: '北京',
    name: '北京市慧慈医院',
    link: 'http://beijing0551681.11467.com/',
  },
  { city: '北京', name: '北京五洲女子医院', link: 'http://www.bjwzfh.com/' },
  { city: '北京', name: '北京圣保罗男子医院', link: 'http://1193410.01p.com/' },
  { city: '北京', name: '北京恒安中医院', link: 'http://www.39yi.com.cn/' },
  { city: '北京', name: '北京建国医院', link: 'http://bj.bjjgfk.com/' },
  {
    city: '北京',
    name: '北京国际医疗中心',
    link: 'http://www.imcclinics.com/',
  },
  {
    city: '北京',
    name: '北京天伦不孕不育医院',
    link: 'http://www.tlbaby.com/',
  },
  { city: '北京', name: '北京玛丽妇婴医院', link: 'http://www.mary.net.cn/' },
  {
    city: '北京',
    name: '北京美联臣医疗美容医院',
    link: 'http://www.mlcbj.com/?pz',
  },
  { city: '北京', name: '北京慧中医院', link: '' },
  {
    city: '北京',
    name: '北京阳光丽人妇科医院',
    link: 'http://3511121.czvv.com/',
  },
  { city: '北京', name: '北京京城皮肤病医院', link: 'http://www.pf110.com/' },
  { city: '北京', name: '北京京北医院', link: 'http://www.bjjbyy.com/' },
  { city: '北京', name: '北京瑞京糖尿病医院', link: '' },
  {
    city: '北京',
    name: '北京众安康中医骨科',
    link: 'http://01059101155.alibole.com/',
  },
  { city: '北京', name: '北京麦瑞骨科医院', link: '' },
  { city: '北京', name: '北京健宫医院', link: '' },
  {
    city: '北京',
    name: '北京华医中西医结合皮肤病医院',
    link: 'http://www.hy120.com/',
  },
  { city: '北京', name: '北京德胜门中医院', link: 'http://www.dsmzyy.com/' },
  { city: '北京', name: '北京军都医院', link: 'http://www.jdzf120.com/' },
  { city: '苏州', name: '苏州东吴医院', link: '' },
  { city: '苏州', name: '苏州华美美莱整形医院', link: '' },
  { city: '苏州', name: '昆山虹桥医院', link: '' },
  { city: '苏州', name: '常熟东方妇科医院', link: '' },
  { city: '苏州', name: '常熟仁爱医院', link: '' },
  { city: '苏州', name: '昆山阳光医院', link: '' },
  { city: '苏州', name: '苏州圣爱医院', link: '' },
  { city: '苏州', name: '苏州新医科', link: '' },
  { city: '天津', name: '天津坤如玛丽医院', link: '' },
  { city: '天津', name: '天津华北医院', link: '' },
  { city: '天津', name: '天津华厦医院', link: '' },
  { city: '天津', name: '天津丽人女子医院', link: '' },
  { city: '天津', name: '天津华山医院', link: '' },
  { city: '天津', name: '天津怡泰生殖专科医院', link: '' },
  { city: '天津', name: '天津现代女子医院', link: '' },
  { city: '天津', name: '天津怡泰医院', link: '' },
  { city: '天津', name: '天津乐园医院', link: '' },
  { city: '天津', name: '天津长庚耳鼻喉', link: '' },
  { city: '广州', name: '广州华美美莱整形医院', link: '' },
  { city: '广州', name: '广州现代医院', link: '' },
  { city: '广州', name: '广州长安医院', link: '' },
  { city: '广州', name: '广州益寿医院', link: '' },
  { city: '广州', name: '广州利德医院', link: '' },
  { city: '广州', name: '番禺东方俪人医院', link: '' },
  { city: '广州', name: '番禺玛莉亚肛肠医院', link: '' },
  { city: '广州', name: '广州圣亚泌尿外科医院', link: '' },
  { city: '广州', name: '广州女子医院', link: '' },
  { city: '广州', name: '广州市江南医院', link: '' },
  { city: '广州', name: '广州济慈医院', link: '' },
  { city: '广州', name: '广东民安医院', link: '' },
  { city: '广州', name: '广州长泰医院', link: '' },
  { city: '广州', name: '广州健安医院', link: '' },
  { city: '广州', name: '广州458医院', link: '' },
  { city: '广州', name: '广州花都人爱医院', link: '' },
  { city: '广州', name: '广州远东美容医院', link: '' },
  { city: '珠海', name: '珠海惠爱医院', link: '' },
  { city: '珠海', name: '珠海九龙医院', link: '' },
  { city: '珠海', name: '珠海阳光医院', link: '' },
  { city: '惠州', name: '惠州仁德妇科医院', link: '' },
  { city: '惠州', name: '惠阳女子医院', link: '' },
  { city: '惠州', name: '惠州东江泌尿专科医院', link: '' },
  { city: '中山', name: '中山现代妇科医院', link: '' },
  { city: '中山', name: '中山市国丹中医院', link: '' },
  { city: '中山', name: '中山和平中医院', link: '' },
  { city: '中山', name: '中山阳光医院', link: '' },
  { city: '汕头', name: '汕头妇产医院', link: '' },
  { city: '东莞', name: '东莞现代妇科医院', link: '' },
  { city: '东莞', name: '塘厦康桥医院', link: '' },
  { city: '东莞', name: '东莞常平医院', link: '' },
  { city: '东莞', name: '东莞康桥妇科医院', link: '' },
  { city: '东莞', name: '东莞乌沙医院', link: '' },
  { city: '东莞', name: '东莞万福妇产医院', link: '' },
  { city: '东莞', name: '东莞南华妇科医院', link: '' },
  { city: '东莞', name: '东莞东方泌尿专科医院', link: '' },
  { city: '江门', name: '江门玛丽妇科医院', link: '' },
  { city: '江门', name: '江门福康医院', link: '' },
  { city: '肇庆', name: '肇庆福康医院', link: '' },
  { city: '佛山', name: '佛山三水女子医院', link: '' },
  { city: '佛山', name: '顺德广济中医院', link: '' },
  { city: '佛山', name: '顺德新世纪泌尿医院', link: '' },
  { city: '佛山', name: '顺德庄头医院', link: '' },
  { city: '佛山', name: '顺德阳光康复医院', link: '' },
  { city: '深圳', name: '深圳美莱美容医院', link: '' },
  { city: '深圳', name: '深圳福华中西医结合医院', link: '' },
  { city: '深圳', name: '深圳博爱医院', link: '', link: '' },
  { city: '深圳', name: '深圳曙光医院', link: '' },
  { city: '深圳', name: '深圳远东妇儿科医院', link: '' },
  { city: '深圳', name: '深圳仁爱医院', link: '' },
  { city: '深圳', name: '深圳和美妇儿科医院', link: '' },
  { city: '深圳', name: '深圳仁康医院', link: '' },
  { city: '深圳', name: '深圳罗岗医院', link: '' },
  { city: '深圳', name: '深圳雪象医院', link: '' },
  { city: '深圳', name: '深圳健安医院', link: '' },
  { city: '深圳', name: '深圳华南妇科医院', link: '' },
  { city: '深圳', name: '深圳国瑞泌尿外科医院', link: '' },
  { city: '深圳', name: '深圳韩美医疗美容医院', link: '' },
  { city: '深圳', name: '深圳健丰医院', link: '' },
  { city: '深圳', name: '深圳龙济医院', link: '' },
  { city: '深圳', name: '深圳同仁妇科医院', link: '' },
  { city: '深圳', name: '深圳凤凰医院', link: '' },
  { city: '深圳', name: '深圳阳光医院', link: '' },
  { city: '昆明', name: '昆明华美美莱整形医院', link: '' },
  { city: '昆明', name: '云南玛莉亚女子医院', link: '' },
  { city: '昆明', name: '云南玛莉亚医院', link: '' },
  { city: '昆明', name: '昆明西昌路医院', link: '' },
  { city: '昆明', name: '昆明阳光医院', link: '' },
  { city: '昆明', name: '昆明仁爱医院', link: '' },
  { city: '昆明', name: '昆明九州医院', link: '' },
  { city: '昆明', name: '解放军478医院妇产中心', link: '' },
  { city: '昆明', name: '昆明九州泌尿医院', link: '' },
  { city: '玉溪', name: '玉溪九州医院', link: '' },
  { city: '曲靖', name: '富源阳光医院', link: '' },
  { city: '曲靖', name: '曲靖九州医院', link: '' },
  { city: '重庆', name: '重庆华美美莱整形医院', link: '' },
  { city: '重庆', name: '重庆华山中医乳腺病医院', link: '' },
  { city: '重庆', name: '重庆坤如玛丽医院', link: '' },
  { city: '重庆', name: '重庆现代女子医院', link: '' },
  { city: '重庆', name: '重庆都市丽人医院', link: '' },
  { city: '重庆', name: '重庆万州博生医院', link: '' },
  { city: '重庆', name: '重庆万州美妇产医院', link: '' },
  { city: '重庆', name: '涪陵博生和美妇产医院', link: '' },
  { city: '重庆', name: '重庆市爱德华医院', link: '' },
  { city: '重庆', name: '重庆五洲女子医院', link: '' },
  { city: '重庆', name: '重庆安琪儿妇产医院', link: '' },
  { city: '重庆', name: '第三军医大学重庆新桥医院', link: '' },
  { city: '重庆', name: '重庆阳光医院', link: '' },
  { city: '重庆', name: '万州阳光眼科医院', link: '' },
  { city: '重庆', name: '重庆爱德华医院', link: '' },
  { city: '重庆', name: '重庆生殖健康医院', link: '' },
  { city: '重庆', name: '重庆红楼医院', link: '' },
  { city: '重庆', name: '解放军第324医院', link: '' },
  { city: '重庆', name: '涪陵三峡医院', link: '' },
  { city: '重庆', name: '重庆红十字会医院', link: '' },
  { city: '成都', name: '成都长征医院', link: '' },
  { city: '成都', name: '成都博爱医院', link: '' },
  { city: '成都', name: '成都丽人女子医院', link: '' },
  { city: '成都', name: '成都华美美莱整形医院', link: '' },
  { city: '成都', name: '四川华美紫馨医学美容医院', link: '' },
  { city: '成都', name: '成都安琪儿妇产医院', link: '' },
  { city: '成都', name: '成都蜀都乳腺医院', link: '' },
  { city: '成都', name: '成都糖尿病专科医院', link: '' },
  { city: '成都', name: '成都曙光男科医院', link: '' },
  { city: '成都', name: '成都玛利亚妇产医院', link: '' },
  { city: '成都', name: '成都欧亚男科医院', link: '' },
  { city: '成都', name: '四川阳光妇科医院', link: '' },
  { city: '成都', name: '成都康新妇科医院', link: '' },
  { city: '成都', name: '成都济民女子医院', link: '' },
  { city: '成都', name: '成都糖尿病专科医院', link: '' },
  { city: '雅安', name: '解放军第三十七医院', link: '' },
  { city: '遵义', name: '遵义女子医院', link: '' },
  { city: '凉山', name: '凉山妇产医院', link: '' },
  { city: '凉山', name: '凉山男科医院', link: '' },
  { city: '南充', name: '南充解放军51医院', link: '' },
  { city: '乐山', name: '武警四川总队医院', link: '' },
  { city: '福州', name: '福州华美美莱整形医院', link: '' },
  { city: '福州', name: '福州鼓楼医院', link: '' },
  { city: '福州', name: '福州现代妇产医院', link: '' },
  { city: '福州', name: '福州左海医院', link: '' },
  { city: '福州', name: '福州总医院第二附属医院', link: '' },
  { city: '福州', name: '福清阳光女子医院', link: '' },
  { city: '福州', name: '福州东南女子医院', link: '' },
  { city: '福州', name: '福州福兴妇产医院', link: '' },
  { city: '福州', name: '福州誉盛医院', link: '' },
  { city: '舟山', name: '舟山现代妇科医院', link: '' },
  { city: '舟山', name: '舟山市千岛医院', link: '' },
  { city: '舟山', name: '舟山市千岛医院妇产科', link: '' },
  { city: '厦门', name: '厦门登特口腔医院', link: '' },
  { city: '厦门', name: '厦门友好妇科', link: '' },
  { city: '厦门', name: '厦门湖里康乐门诊部', link: '' },
  { city: '莆田', name: '莆田丽人妇科医院', link: '' },
  { city: '莆田', name: '莆田盛兴医院', link: '' },
  { city: '莆田', name: '莆田中西医肛肠医院', link: '' },
  { city: '莆田', name: '莆田口腔医院', link: '' },
  { city: '宁波', name: '宁波美莱整形美容医院', link: '' },
  { city: '宁波', name: '宁波博爱医院', link: '' },
  { city: '宁波', name: '宁波虹桥医院', link: '' },
  { city: '宁波', name: '宁波欧亚男科医院', link: '' },
  { city: '宁波', name: '宁波甬城医院', link: '' },
  { city: '宁波', name: '慈溪圣爱医院', link: '' },
  { city: '杭州', name: '杭州新东方妇产科医院', link: '' },
  { city: '杭州', name: '杭州玛莉亚妇女医院', link: '' },
  { city: '杭州', name: '杭州虹桥医院', link: '' },
  { city: '杭州', name: '杭州建国医院', link: '' },
  { city: '杭州', name: '杭州天目山医院', link: '' },
  { city: '杭州', name: '杭州萧山九龙男科医院', link: '' },
  { city: '杭州', name: '杭州广仁医院', link: '' },
  { city: '杭州', name: '杭州阿波罗男子医院', link: '' },
  { city: '杭州', name: '杭州和睦医院', link: '' },
  { city: '杭州', name: '杭州真爱医院', link: '' },
  { city: '杭州', name: '杭州瑞丽医疗美容医院', link: '' },
  { city: '杭州', name: '杭州同济医院', link: '' },
  { city: '湖州', name: '湖州阳光女子医院', link: '' },
  { city: '泉州', name: '泉州华美美莱整形医院', link: '' },
  { city: '泉州', name: '泉州南亚华侨医院', link: '' },
  { city: '泉州', name: '泉州新阳光女子医院', link: '' },
  { city: '泉州', name: '泉州坤如玛丽医院', link: '' },
  { city: '泉州', name: '泉州南亚医院', link: '' },
  { city: '金华', name: '浙江金华博康生殖医院', link: '' },
  { city: '嘉兴', name: '浙江新安国际医院', link: '' },
  { city: '嘉兴', name: '嘉兴曙光中西医结合医院', link: '' },
  { city: '嘉兴', name: '嘉兴博爱医院', link: '' },
  { city: '嘉兴', name: '嘉兴曙光中西医结合医院', link: '' },
  { city: '台州', name: '温岭和平医院', link: '' },
  { city: '温州', name: '瑞安华东医院', link: '' },
  { city: '温州', name: '温州长征医院', link: '' },
  { city: '温州', name: '温州协和医院', link: '' },
  { city: '温州', name: '温州建国医院', link: '' },
  { city: '温州', name: '温州红旗医院', link: '' },
  { city: '温州', name: '温州爱尔五官科医院', link: '' },
  { city: '龙岩', name: '龙岩女子医院', link: '' },
  { city: '龙岩', name: '龙岩阳光医院', link: '' },
  { city: '济南', name: '山东东方男科医院', link: '' },
  { city: '济南', name: '山东紫荆花医院', link: '' },
  { city: '济南', name: '山东红十字会医院', link: '' },
  { city: '济南', name: '济南一零六医院', link: '' },
  { city: '济南', name: '济南中医不孕不育医院', link: '' },
  { city: '济南', name: '济南中医白癜风医院', link: '' },
  { city: '济南', name: '济南中医精神病医院', link: '' },
  { city: '济南', name: '济南中医肝病医院', link: '' },
  { city: '济南', name: '济南中医静脉曲张医院', link: '' },
  { city: '济南', name: '济南中医风湿病医院', link: '' },
  { city: '济南', name: '济南中山肝病医院', link: '' },
  { city: '济南', name: '济南中德骨科医院', link: '' },
  { city: '济南', name: '济南中研皮肤病医院', link: '' },
  { city: '济南', name: '济南九龙泌尿专科医院', link: '' },
  { city: '济南', name: '济南乳腺医院', link: '' },
  { city: '济南', name: '济南乳腺病医院', link: '' },
  { city: '济南', name: '济南五洲医院', link: '' },
  { city: '济南', name: '济南六一天使儿童医院', link: '' },
  { city: '济南', name: '济南华夏医院', link: '' },
  { city: '济南', name: '济南协和肝病医院', link: '' },
  { city: '济南', name: '济南和谐妇科医院', link: '' },
  { city: '济南', name: '济南哮喘病医院', link: '' },
  { city: '济南', name: '济南圣玛利亚妇产医院', link: '' },
  { city: '济南', name: '济南坤如玛丽医院', link: '' },
  { city: '济南', name: '济南复元康复医院', link: '' },
  { city: '济南', name: '济南妇科医院', link: '' },
  { city: '济南', name: '济南整形美容医院', link: '' },
  { city: '济南', name: '济南泉城医院', link: '' },
  { city: '济南', name: '济南海峡美容整形医院', link: '' },
  { city: '济南', name: '济南现代皮肤病医院', link: '' },
  { city: '济南', name: '济南白癜风医院', link: '' },
  { city: '济南', name: '济南真爱妇科医院', link: '' },
  { city: '济南', name: '济南神康医院', link: '' },
  { city: '济南', name: '济南美莱整形医院', link: '' },
  { city: '济南', name: '济南耳鼻喉医院', link: '' },
  { city: '济南', name: '济南肛肠医院', link: '' },
  { city: '济南', name: '济南股骨头医院', link: '' },
  { city: '济南', name: '济南肾病医院', link: '' },
  { city: '济南', name: '济南胃肠病医院', link: '' },
  { city: '济南', name: '济南血液病医院', link: '' },
  { city: '济南', name: '济南银屑病医院', link: '' },
  { city: '济南', name: '济南阳光女子医院', link: '' },
  { city: '济南', name: '济南集美美容整形医院', link: '' },
  { city: '济南', name: '济南青华不孕不育医院', link: '' },
  { city: '济南', name: '济南骨科医院', link: '' },
  { city: '济南', name: '解放军第三七一中心医院', link: '' },
  { city: '潍坊', name: '潍坊博爱医院', link: '' },
  { city: '潍坊', name: '潍坊长安医院', link: '' },
  { city: '潍坊', name: '潍坊和平医院', link: '' },
  { city: '青岛', name: '青岛妇婴医院', link: '' },
  { city: '青岛', name: '青岛玛丽妇产医院', link: '' },
  { city: '青岛', name: '青岛长征院', link: '' },
  { city: '青岛', name: '青岛曙光男科医院', link: '' },
  { city: '青岛', name: '山东青岛曙光医院', link: '' },
  { city: '青岛', name: '青岛集美整形美容医院', link: '' },
  { city: '青岛', name: '青岛新阳光医院', link: '' },
  { city: '德州', name: '齐河阳光医院', link: '' },
  { city: '威海', name: '威海现代女子医院', link: '' },
  { city: '聊城', name: '聊城东昌府三医院', link: '' },
  { city: '淄博', name: '山东淄博金盾医院', link: '' },
  { city: '淄博', name: '淄博女子医院', link: '' },
  { city: '哈尔滨', name: '黑龙江玛丽亚妇产医院', link: '' },
  { city: '哈尔滨', name: '黑龙江东北医院', link: '' },
  { city: '哈尔滨', name: '黑龙江和平医院', link: '' },
  { city: '哈尔滨', name: '黑龙江和美妇产医院', link: '' },
  { city: '哈尔滨', name: '哈尔滨市生殖保健中心院', link: '' },
  { city: '哈尔滨', name: '哈尔滨欧亚男科医院', link: '' },
  { city: '哈尔滨', name: '黑龙江长庚耳鼻喉医院', link: '' },
  { city: '哈尔滨', name: '黑龙江阳光女子医院', link: '' },
  { city: '哈尔滨', name: '黑龙江省武警黄金医院妇科', link: '' },
  { city: '长春', name: '长春同济医院', link: '' },
  { city: '长春', name: '吉林总队医院', link: '' },
  { city: '长春', name: '长春长庚耳鼻喉医院', link: '' },
  { city: '长春', name: '长春阳光女子医院', link: '' },
  { city: '长春', name: '长春阳光口腔医院', link: '' },
  { city: '四平', name: '四平阳光医院', link: '' },
  { city: '延边', name: '延吉博生现代妇科医院', link: '' },
  { city: '沈阳', name: '沈阳北陵医院', link: '' },
  { city: '沈阳', name: '沈阳曙光男科医院', link: '' },
  { city: '沈阳', name: '武警辽宁省总队医院', link: '' },
  { city: '沈阳', name: '解放军沈阳463医院希美整形美容', link: '' },
  { city: '大连', name: '大连长城妇科医院', link: '' },
  { city: '大连', name: '大连新世纪医院', link: '' },
  { city: '大连', name: '大连阳光医院', link: '' },
  { city: '无锡', name: '无锡玛丽亚医院', link: '' },
  { city: '无锡', name: '无锡嘉仕恒信医院', link: '' },
  { city: '无锡', name: '无锡南站医院', link: '' },
  { city: '无锡', name: '无锡虹桥医院', link: '', link: '' },
  { city: '无锡', name: '江阴东方女子医院', link: '' },
  { city: '无锡', name: '宜兴武警医院', link: '' },
  { city: '无锡', name: '江阴九龙泌尿外科医院', link: '' },
  { city: '无锡', name: '无锡新区医院', link: '' },
  { city: '南京', name: '江苏施尔美整形美容医院', link: '' },
  { city: '南京', name: '南京曙光医院', link: '' },
  { city: '南京', name: '南京江宁博爱医院', link: '' },
  { city: '南京', name: '南京市江宁区众彩门诊部', link: '', link: '' },
  { city: '南京', name: '南京世纪现代妇产医院（南院、东院）', link: '' },
  { city: '南京', name: '南京建国男科医院', link: '' },
  { city: '南京', name: '南京康豪妇科', link: '' },
  { city: '南京', name: '南京阳光肿瘤医院', link: '' },
  { city: '南京', name: '南京港龙医院', link: '' },
  { city: '南京', name: '454医院植发科', link: '' },
  { city: '南京', name: '南京长江医院植发科', link: '' },
  { city: '南京', name: '南京医科二附院协作医院', link: '' },
  { city: '南京', name: '天长现代妇产医院', link: '' },
  { city: '南京', name: '南京医科大学附属友谊整形外科医院', link: '' },
  { city: '南京', name: '南京解放军81医院', link: '' },
  { city: '南京', name: '南京454医院妇产科', link: '' },
  { city: '南京', name: '南京蓝十字脑科医院', link: '' },
  { city: '南京', name: '南京迈皋桥医院', link: '' },
  { city: '南京', name: '南京东院门诊部', link: '' },
  { city: '南京', name: '南京华美整形美容医院', link: '' },
  { city: '南京', name: '南京空军机关医院神经科', link: '' },
  { city: '南京', name: '南京军区机关医院妇科', link: '' },
  { city: '南京', name: '南京长江医院', link: '' },
  { city: '南京', name: '南京长海医院', link: '' },
  { city: '南京', name: '南京美迪亚医院', link: '' },
  { city: '南京', name: '南京亚韩整形美容医院', link: '' },
  { city: '南京', name: '南京仁品耳鼻喉专科医院', link: '' },
  { city: '南京', name: '南京邦德骨科医院', link: '' },
  { city: '南京', name: '南京肛泰中医院', link: '' },
  { city: '南京', name: '南京维多利亚美容诊所', link: '' },
  { city: '张家港', name: '张家港朝阳五官科医院', link: '' },
  { city: '盐城', name: '盐城协和康复医院', link: '' },
  { city: '泰州', name: '江苏泰州红房子医院', link: '' },
  { city: '泰州', name: '泰州市海陵医院', link: '' },
  { city: '泰州', name: '泰州海陵女子医院', link: '' },
  { city: '宿迁', name: '宿迁市妇产医院', link: '' },
  { city: '宿迁', name: '泗洪阳光儿童医院', link: '' },
  { city: '淮安', name: '江苏淮安中山医院', link: '' },
  { city: '淮安', name: '淮安中山医院', link: '' },
  { city: '淮安', name: '淮安生殖医院', link: '' },
  { city: '南通', name: '江苏海安华山医院', link: '' },
  { city: '南通', name: '南通和美家妇产科医院', link: '' },
  { city: '南通', name: '南通长城医院', link: '' },
  { city: '武汉', name: '武汉华夏医院', link: '' },
  { city: '武汉', name: '武汉华美医院', link: '' },
  { city: '武汉', name: '武汉现代女子妇科医院', link: '' },
  { city: '武汉', name: '武汉当代佳丽医院', link: '' },
  { city: '武汉', name: '湖北荣军医院', link: '' },
  { city: '武汉', name: '武汉阳光女子医院', link: '' },
  { city: '武汉', name: '武汉华仁医院', link: '' },
  { city: '荆州', name: '荆州华康医院', link: '' },
  { city: '黄冈', name: '黄冈泌尿专科医院', link: '' },
  { city: '黄石', name: '湖北黄石福康医院', link: '' },
  { city: '襄阳', name: '襄阳市第五人民医院', link: '' },
  { city: '襄阳', name: '襄阳东大肛肠医院', link: '' },
  { city: '襄阳', name: '襄阳仁爱女子医院', link: '' },
  { city: '乌海', name: '乌海现代医院', link: '' },
  { city: '呼和浩特', name: '内蒙古天骄医院', link: '' },
  { city: '呼和浩特', name: '呼和浩特五洲女子医院', link: '' },
  { city: '贵阳', name: '贵州退休医师医院', link: '' },
  { city: '贵阳', name: '贵阳五官中心', link: '' },
  { city: '贵阳', name: '贵阳长江医院', link: '' },
  { city: '贵阳', name: '贵阳和谐阳光医院', link: '' },
  { city: '贵阳', name: '贵阳马王庙医院', link: '' },
  { city: '贵阳', name: '贵阳现代女子医院', link: '' },
  { city: '贵阳', name: '贵阳和美妇产医院', link: '' },
  { city: '铜仁', name: '铜仁华夏医院', link: '' },
  { city: '安顺', name: '安顺阳光妇科医院', link: '' },
  { city: '毕节', name: '毕节现代医院', link: '' },
  { city: '长沙', name: '长沙华夏医院', link: '', link: '' },
  { city: '长沙', name: '长沙湘江医院七大医院', link: '' },
  { city: '长沙', name: '长沙阳光医院', link: '' },
  { city: '长沙', name: '长沙仁爱医院', link: '' },
  { city: '长沙', name: '长沙恒生手外科医院', link: '' },
  { city: '长沙', name: '长沙博大泌尿专科医院', link: '' },
  { city: '长沙', name: '长沙南方骨外科医院', link: '' },
  { city: '长沙', name: '长沙现代女子医院', link: '' },
  { city: '长沙', name: '长沙丽人妇产医院', link: '' },
  { city: '长沙', name: '长沙阳光医院', link: '' },
  { city: '长沙', name: '武警湖南省总队医院', link: '' },
  { city: '郴州', name: '湖南郴州福康医院', link: '' },
  { city: '湘潭', name: '湘潭阳光眼科中心', link: '' },
  { city: '娄底', name: '娄底阳光医院', link: '' },
  { city: '南昌', name: '南昌市第五医院', link: '' },
  { city: '南昌', name: '南昌仁爱女子医院', link: '' },
  { city: '南昌', name: '南昌曙光手足外科医院', link: '' },
  { city: '南昌', name: '南昌佳美美容医院', link: '' },
  { city: '南昌', name: '南昌华山不孕不育医院', link: '' },
  { city: '南昌', name: '南昌博爱泌尿专科医院', link: '' },
  { city: '南昌', name: '南昌东大肛肠专科医院', link: '' },
  { city: '南昌', name: '南昌博大耳鼻咽喉专科医院', link: '' },
  { city: '南昌', name: '南昌泌尿专科医院', link: '' },
  { city: '南昌', name: '南昌仁爱女子医院', link: '' },
  { city: '九江', name: '九江玛丽亚医院', link: '' },
  { city: '九江', name: '九江新世纪医院', link: '' },
  { city: '九江', name: '九江阳光女子医院', link: '' },
  { city: '吉安', name: '江西吉安市第二人民医院', link: '' },
  { city: '萍乡', name: '萍乡市新世纪泌尿专科医院', link: '' },
  { city: '萍乡', name: '萍乡妇科医院', link: '' },
  { city: '赣州', name: '赣州现代泌尿专科医院', link: '' },
  { city: '上饶', name: '上饶东大肛肠专科医院', link: '' },
  { city: '上饶', name: '上饶协和医院', link: '' },
  { city: '太原', name: '山西现代妇产医院', link: '' },
  { city: '太原', name: '山西民生医院', link: '' },
  { city: '太原', name: '太原糖尿病专科医院', link: '' },
  { city: '太原', name: '太原新医医院', link: '' },
  { city: '太原', name: '太原益民中医院', link: '' },
  { city: '太原', name: '武警山西总队医院', link: '' },
  { city: '太原', name: '山西长庚耳鼻喉医院', link: '' },
  { city: '太原', name: '太原糖尿病专科医院', link: '' },
  { city: '太原', name: '太原新医医院', link: '' },
  { city: '太原', name: '太原益民中医院', link: '' },
  { city: '太原', name: '太原白癜风医院', link: '', link: '' },
  { city: '临汾', name: '临汾现代女子医院', link: '' },
  { city: '阳泉', name: '山西阳泉东方生殖医院', link: '' },
  { city: '长治', name: '长治女子医院', link: '' },
  { city: '大同', name: '大同新时代妇科医院', link: '' },
  { city: '晋城', name: '晋城现代女子医院', link: '', link: '' },
  { city: '晋城', name: '晋城生殖医院', link: '' },
  { city: '晋中', name: '山西新阳光妇科医院', link: '' },
  { city: '运城', name: '运城禹都人民医院', link: '' },
  { city: '运城', name: '运城禹都人民医院', link: '' },
  { city: '西安', name: '西安俪人医院', link: '' },
  { city: '西安', name: '武警陕西总队医院', link: '' },
  { city: '西安', name: '西安阳光医院', link: '' },
  { city: '包头', name: '包头现代女子妇产医院', link: '' },
  { city: '蚌埠', name: '澳美佳女子医院', link: '' },
  { city: '蚌埠', name: '蚌埠解放军一二三中心医院', link: '' },
  { city: '亳州', name: '涡阳阳光医院', link: '' },
  { city: '芜湖', name: '芜湖阳光眼科医院' },
  { city: '芜湖', name: '芜湖丹凤朝阳妇科医院', link: '' },
  { city: '巢湖', name: '巢湖康平妇产医院', link: '' },
  { city: '巢湖', name: '巢湖阳光妇幼医院', link: '', link: '' },
  { city: '淮北', name: '淮北女子医院', link: '' },
  { city: '淮北', name: '淮北阳光心理院', link: '' },
  { city: '合肥', name: '合肥市中山医院', link: '' },
  { city: '合肥', name: '合肥九龙男科医院', link: '' },
  { city: '合肥', name: '合肥丹凤朝阳妇科医院', link: '' },
  { city: '合肥', name: '合肥105医院', link: '' },
  { city: '安阳', name: '安阳协和医院', link: '' },
  { city: '郑州', name: '河南中都皮肤病医院', link: '' },
  { city: '郑州', name: '河南省军区医院', link: '' },
  { city: '郑州', name: '郑州集美整形美容医院', link: '' },
  { city: '郑州', name: '郑州华夏白癜风医院', link: '' },
  { city: '郑州', name: '巩义阳光医院', link: '' },
  { city: '郑州', name: '郑州华山医院', link: '' },
  { city: '许昌', name: '许昌新时代妇科医院', link: '' },
  { city: '许昌', name: '许昌凤凰医院', link: '' },
  { city: '许昌', name: '许昌中山医院', link: '' },
  { city: '廊坊', name: '廊坊万福医院', link: '', link: '' },
  { city: '廊坊', name: '廊坊世纪协和医院', link: '' },
  { city: '保定', name: '保定京津医院', link: '' },
  { city: '保定', name: '保定世纪协和医院', link: '' },
  { city: '保定', name: '保定长安医院', link: '' },
  { city: '保定', name: '保定现代女子医院', link: '' },
  { city: '保定', name: '保定白癜风医院', link: '' },
  { city: '唐山', name: '唐山京城皮肤病医院', link: '' },
  { city: '唐山', name: '唐山女子医院', link: '' },
  { city: '唐山', name: '唐山红十字医院', link: '' },
  { city: '洛阳', name: '洛阳牡丹女子医院', link: '' },
  { city: '洛阳', name: '解放军534医院', link: '' },
  { city: '洛阳', name: '洛阳牡丹女子医院', link: '' },
  { city: '信阳', name: '信阳泌尿外科医院', link: '' },
  { city: '平顶山', name: '平顶山市武警医院', link: '' },
  { city: '漯河', name: '漯河东方医院', link: '' },
  { city: '石家庄', name: '河北东方中西医结合医院', link: '' },
  { city: '石家庄', name: '石家庄美联臣医疗美容医院', link: '' },
  { city: '邯郸', name: '邯郸仁爱妇科医院', link: '' },
  { city: '西藏', name: '西藏博爱医院', link: '' },
  { city: '西藏', name: '拉萨北大泌尿生殖医院', link: '' },
  { city: '银川', name: '宁夏西京妇产医院', link: '' },
  { city: '兰州', name: '兰州仁和医院', link: '' },
  { city: '桂林', name: '广西阳光医院', link: '' },
  { city: '桂林', name: '桂林阳光医院', link: '' },
  { city: '柳州', name: '柳州福康医院', link: '' },
  { city: '伊犁', name: '伊犁阳光女子医院', link: '' },
  { city: '伊宁', name: '伊宁阳光女子医院', link: '' },
  { city: '乌鲁木齐', name: '新彊维吾尔自治区人民医院肿瘤中心', link: '' },
  { city: '乌鲁木齐', name: '新疆爱德华医院', link: 'http://www.wsnkyy.com/' },
  { city: '西宁', name: '青海西宁莆田友谊医院', link: 'javascript:;' },
  { city: '西宁', name: '西宁现代妇产医院', link: 'http://www.6251111.com/' },
  { city: '海口', name: '武警海南总队医院妇科中心', link: 'javascript:;' },
];

var city = [
  {
    p: '浙江',
    city: ['杭州', '宁波', '温州', '嘉兴', '湖州', '金华', '舟山', '台州'],
  },
  { p: '北京', city: ['北京'] },
  { p: '上海', city: ['上海'] },
  { p: '天津', city: ['天津'] },
  { p: '重庆', city: ['重庆'] },
  { p: '河北', city: ['石家庄', '保定', '唐山', '廊坊', '邯郸'] },
  { p: '山西', city: ['太原', '临汾', '大同', '晋中', '晋城', '运城', '长治'] },
  { p: '内蒙', city: ['呼和浩特', '乌海', '包头'] },
  { p: '辽宁', city: ['沈阳', '大连'] },
  { p: '吉林', city: ['长春', '四平', '延边'] },
  { p: '黑龙江', city: ['哈尔滨'] },
  {
    p: '江苏',
    city: [
      '南京',
      '南通',
      '宿迁',
      '张家港',
      '无锡',
      '泰州',
      '淮安',
      '盐城',
      '苏州',
    ],
  },
  { p: '安徽', city: ['合肥', '亳州', '巢湖', '淮北', '芜湖', '蚌埠'] },
  { p: '福建', city: ['厦门', '泉州', '福州', '莆田', '龙岩'] },
  { p: '江西', city: ['南昌', '上饶', '九江', '吉安', '萍乡', '赣州'] },
  { p: '山东', city: ['济南', '青岛', '威海', '德州', '淄博', '潍坊', '聊城'] },
  {
    p: '河南',
    city: ['郑州', '信阳', '安阳', '平顶山', '洛阳', '漯河', '许昌'],
  },
  { p: '湖北', city: ['武汉', '荆州', '襄阳', '黄冈', '黄石'] },
  { p: '湖南', city: ['长沙', '娄底', '湘潭', '郴州'] },
  {
    p: '广东',
    city: [
      '广州',
      '东莞',
      '中山',
      '佛山',
      '惠州',
      '汕头',
      '江门',
      '肇庆',
      '深圳',
      '珠海',
    ],
  },
  { p: '广西', city: ['桂林', '柳州'] },
  { p: '海南', city: ['海口'] },
  { p: '四川', city: ['成都', '乐山', '凉山', '南充', '雅安'] },
  { p: '贵州', city: ['贵阳', '安顺', '毕节', '遵义', '铜仁'] },
  { p: '云南', city: ['昆明', '曲靖', '玉溪'] },
  { p: '西藏', city: ['拉萨'] },
  { p: '陕西', city: ['西安', '阳泉'] },
  { p: '甘肃', city: ['兰州'] },
  { p: '青海', city: ['西宁'] },
  { p: '宁夏', city: ['银川'] },
  { p: '新疆', city: ['乌鲁木齐', '伊宁', '伊犁'] },
];

var G = {
  init: function () {
    var self = this;
    self.getData('北京');
    self.bindEvent();
  },
  bindEvent: function () {
    var btn = $('.j_search');
    var p = $('#province');
    p.on('change', function () {
      var province = $('#province').val();
      // console.log(province);
      for (var i in city) {
        if (city[i].p == province) {
          // console.log(city[i].city[0]);
          G.getData(city[i].city[0]);
        }
        if (city[i].p !== province) continue;
        var cities = city[i].city;
        var cityHtml = '';
        cities.forEach(function (c) {
          cityHtml += "<option value='" + c + "'>" + c + '</option>';
        });
        $('#city').html(cityHtml);
      }
    });

    $('#city').on('change', function () {
      var city = $('#city').val();
      G.getData(city);
    });
  },
  getData: function (city) {
    var content = '';
    for (var i in data) {
      var item = data[i];
      var d_city = item.city;
      if (d_city != city) continue;

      content += "<p><span class='hospital-name'>" + item.name + '</span></p>';
    }

    content += '';
    $('#content').html(content);
  },
};
G.init();
